/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chat/[id]': RouteRecordInfo<
      '/chat/[id]',
      '/chat/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/agents/': RouteRecordInfo<
      '/dashboard/agents/',
      '/dashboard/agents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/agents/[id]': RouteRecordInfo<
      '/dashboard/agents/[id]',
      '/dashboard/agents/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dashboard/errors': RouteRecordInfo<
      '/dashboard/errors',
      '/dashboard/errors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/integrations/mobiwave': RouteRecordInfo<
      '/dashboard/integrations/mobiwave',
      '/dashboard/integrations/mobiwave',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/landing': RouteRecordInfo<
      '/landing',
      '/landing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox': RouteRecordInfo<
      '/sandbox',
      '/sandbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/chat/[id].vue': {
      routes:
        | '/chat/[id]'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/dashboard/agents/index.vue': {
      routes:
        | '/dashboard/agents/'
      views:
        | never
    }
    'src/pages/dashboard/agents/[id].vue': {
      routes:
        | '/dashboard/agents/[id]'
      views:
        | never
    }
    'src/pages/dashboard/errors.vue': {
      routes:
        | '/dashboard/errors'
      views:
        | never
    }
    'src/pages/dashboard/integrations/mobiwave.vue': {
      routes:
        | '/dashboard/integrations/mobiwave'
      views:
        | never
    }
    'src/pages/landing.vue': {
      routes:
        | '/landing'
      views:
        | never
    }
    'src/pages/sandbox.vue': {
      routes:
        | '/sandbox'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
